pipeline {
    agent any

    stages {
        stage('checkout') {
            steps {
                checkout scm
            }
        }
        stage('build') {
            steps {
                sh 'docker build ./world_of_games/ -t ran-flask-app:1.0.4'
            }
        }
        stage('run') {
            steps {
              sh 'docker run -d -p 5000:5000 --name ran-flask-app ran-flask-app:1.0.4'
            }

            {
                sh 'rm ./world_of_games/code/score.txt'
            }
            {
            sh 'echo "18" > ./world_of_games/code/score.txt'
            }
        }
        stage('test') {
            steps {
                sh 'python3 ./world_of_games/code/e2e.py'
            }
        }
        stage('push') {
            steps {
                sh 'docker push ranmalka/ran-flask-app:1.0.4'
            }
        }
    }
}
